name: Build and test ROS1

on:
  push:
  pull_request:
  release:
  repository_dispatch:

jobs:
  build:
    name: "ROS1 ${{ matrix.ros_version }}"
    runs-on: ubuntu-latest
    container:
      image: "rostooling/setup-ros-docker:ubuntu-focal-ros-${{matrix.ros_distribution}}-ros-base-latest"
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - noetic
          - melodic

    steps:
      - name: setup directories
        run: mkdir -p ros_ws/src

      - name: checkout
        uses: actions/checkout@v3
        with:
          path: ros_ws/src

      - uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}

      - name: build and test
        continue-on-error: true
        uses: ros-tooling/action-ros-ci@0.2.2
        with:
          package-name: fields2cover_ros
          target-ros1-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: "${{ github.workspace }}/.github/workflows/f2c_repo.repos"






