name: Build and test ROS2

on:
  push:
  pull_request:
  release:
  repository_dispatch:

jobs:
  build:
    name: "ROS2 ${{ matrix.ros_version }}"
    runs-on: ubuntu-latest
    container: "ros:${{ matrix.ros_version }}"
    strategy:
      fail-fast: false
      matrix:
        ros_version: ["humble"]

    steps:
      - uses: actions/checkout@v3
      - name: Print env
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}

      - uses: lukka/get-cmake@latest
      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update -qq && apt-get install -qqy ca-certificates python3-osrf-pycommon git software-properties-common
          add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable && apt-get update -qq
          mkdir ws/src && cd ws
          git clone https://github.com/Fields2Cover/Fields2Cover.git src/fields2cover --branch main
          rosdep update
          rosdep install -r --ignore-src -y --from-paths .
          bash -c 'source /opt/ros/*/setup.bash && colcon build'

      - name: Copy fields2cover_ros to the src folder
        working-directory: ${{github.workspace}}/ws
        run: cp -r . src/fields2cover_ros/.

      - name: Install ROS dependencies
        working-directory: ${{github.workspace}}/ws
        run: rosdep install -r --ignore-src -y --from-paths .

      - name: Build
        shell: bash
        run: |
          source /opt/ros/*/setup.bash
          colcon build
          colcon test



